<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="C3DES396" ignored="0" name="Regression_TC_30_CIwithPowerspotwith13staticIP_WelcomePackValidation" tests="1" failures="1" timestamp="28 Feb 2018 21:49:35 GMT" time="435.788" errors="0">
  <testcase name="TestCaseExecution" time="423.741" classname="TestDriver.TestExecutionDriver">
    <failure type="java.lang.AssertionError" message=" failed">
      <![CDATA[java.lang.AssertionError:  failed
	at DUMMYDELETEIT.genericDriver.CI_ProductBasketConfiguration(genericDriver.java:582)
	at TestDriver.TestExecutionDriver.TestCaseExecution(TestExecutionDriver.java:206)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- TestCaseExecution -->
</testsuite> <!-- Regression_TC_30_CIwithPowerspotwith13staticIP_WelcomePackValidation -->
