<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="C4LAP149" ignored="0" name="TC_10_OfficeInternet_With_Phone" tests="1" failures="1" timestamp="11 Jan 2018 08:52:23 GMT" time="337.548" errors="0">
  <testcase name="TestCaseExecution" time="278.046" classname="TestDriver.TestExecutionDriver">
    <failure type="java.lang.AssertionError" message=" failed">
      <![CDATA[java.lang.AssertionError:  failed
	at DUMMYDELETEIT.genericDriver.validateOrder(genericDriver.java:600)
	at TestDriver.TestExecutionDriver.TestCaseExecution(TestExecutionDriver.java:187)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- TestCaseExecution -->
</testsuite> <!-- TC_10_OfficeInternet_With_Phone -->
